sonar.projectKey=developerstudioai_taller-arquitectura
sonar.organization=developerstudioai
sonar.projectName=EventFlow Taller Arquitectura
sonar.sources=.
sonar.exclusions=docs/**,infra/**
sonar.sourceEncoding=UTF-8
